name: Lighthouse
on: [pull_request]

jobs:
  Lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - uses: actions/checkout@master
      - name: Lighthouse Audit Feature Branch
        env:
          LHCI_COMMENT_TOKEN: ${{ secrets.LHCI_COMMENT_TOKEN }}
          LHCI_BASE_GITHUB_ACCESS_TOKEN: "${{ github.head_ref }} === 'staging' ? ${{ LHCI_STAGING_GITHUB_ACCESS_TOKEN }} : ${{ LHCI_FEAT_GITHUB_ACCESS_TOKEN }}"
          LHCI_TARGET_GITHUB_ACCESS_TOKEN: "${{ github.head_ref }} === 'staging' ? ${{ LHCI_MASTER_GITHUB_ACCESS_TOKEN }} : ${{ LHCI_STAGING_GITHUB_ACCESS_TOKEN }}"
        uses: foo-software/lighthouse-check-action@master
        with:
          outputDirectory: .
          device: "all"
          urls: "https://receta-git-${{ github.head_ref }}-shorttryan.vercel.app"
          extraHeaders: "{\"Cookie\":\"auth=$LHCI_TARGET_GITHUB_ACCESS_TOKEN\"}"
          prCommentEnabled: true
          prCommentSaveOld: true
          gitHubAccessToken: ${{ secrets.LHCI_COMMENT_TOKEN }}
          gitAuthor: ${{ github.actor }}
          gitBranch: ${{ github.ref }}
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: Lighthouse reports
          path: .
