name: Lighthouse CI
on: [push]

jobs:
  Lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Wait for build to finish
        shell: bash
        run: sleep 100s
        id: stall
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - uses: actions/checkout@master
      - name: Lighthouse
        env:
          LHCI_COMMENT_TOKEN: ${{ secrets.LHCI_COMMENT_TOKEN }}
          LHCI_GITHUB_ACCESS_TOKEN: ${{ secrets.LHCI_GITHUB_ACCESS_TOKEN }}
        uses: foo-software/lighthouse-check-action@master
        with:
          outputDirectory: .
          device: "all"
          urls: "https://receta-git-${{ steps.extract_branch.outputs.branch }}-shorttryan.vercel.app"
          extraHeaders: "{\"Cookie\":\"auth=${{ secrets.LHCI_GITHUB_ACCESS_TOKEN }}\"}"
          gitHubAccessToken: ${{ secrets.LHCI_COMMENT_TOKEN }}
          gitAuthor: ${{ github.actor }}
          gitBranch: ${{ github.ref }}
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: Lighthouse reports
          path: .
