name: Lighthouse
on: [pull_request]

jobs:
  Lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Wait For Remote Build
        shell: bash
        run: sleep 10s
      - name: Create Artifacts Directory
        shell: bash
        run: mkdir artifacts
      - name: Lighthouse Audit Feature Branch
        uses: foo-software/lighthouse-check-action@master
        with:
          outputDirectory: ./artifacts
          device: 'all'
          urls: 'https://receta-git-${{ github.head_ref }}-shorttryan.vercel.app'
          extraHeaders: '{"Cookie":"auth=${{ secrets.LHCI_FEAT_ACCESS_TOKEN }}"}'
          prCommentEnabled: false
          prCommentSaveOld: false
          gitHubAccessToken: ${{ secrets.LHCI_COMMENT_TOKEN }}
      - name: Lighthouse Audit Staging
        uses: foo-software/lighthouse-check-action@master
        with:
          outputDirectory: ./artifacts
          device: 'all'
          urls: 'https://recetastaging.vercel.app'
          extraHeaders: '{"Cookie":"auth=${{ secrets.LHCI_STAGING_ACCESS_TOKEN }}"}'
          prCommentEnabled: true
          prCommentSaveOld: false
          gitHubAccessToken: ${{ secrets.LHCI_COMMENT_TOKEN }}
      - name: Lighthouse Audit Master
        uses: foo-software/lighthouse-check-action@master
        with:
          outputDirectory: ./artifacts
          device: 'all'
          urls: 'https://receta.vercel.app'
          extraHeaders: '{"Cookie":"auth=${{ secrets.LHCI_PROD_ACCESS_TOKEN }}"}'
          prCommentEnabled: false
          prCommentSaveOld: true
          gitHubAccessToken: ${{ secrets.LHCI_COMMENT_TOKEN }}
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: Lighthouse reports
          path: ./artifacts
