name: Lighthouse CI
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#      - name: Wait for build to finish
#        shell: bash
#        run: sleep 70s
#        id: stall
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Generating Lighthouse Report
        uses: treosh/lighthouse-ci-action@v9
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          LHCI_GITHUB_ACCESS_TOKEN: ${{ secrets.LHCI_GITHUB_ACCESS_TOKEN }}
        with:
          urls: |
            "https://receta-git-${{ steps.extract_branch.outputs.branch }}-shorttryan.vercel.app"
          uploadArtifacts: true
          temporaryPublicStorage: true
          runs: 3
          extra-headers: "{\"auth\":\"${{ secrets.LHCI_GITHUB_ACCESS_TOKEN }}\"}"
