name: Lighthouse
on: [pull_request]

jobs:
  Lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Wait For Remote Build
        shell: bash
        run: sleep 100s
      - name: Create Artifacts Directory
        shell: bash
        run: mkdir artifacts
      - name: Lighthouse Audit Feature Branch
        uses: foo-software/lighthouse-check-action@master
        with:
          urls: 'https://receta-git-${{ github.head_ref }}-shorttryan.vercel.app'
          gitAuthor: ${{ github.actor }}
          gitBranch: ${{ github.ref }}
          gitHubAccessToken: ${{ secrets.GITHUB_TOKEN }}
          prCommentEnabled: true
          prCommentSaveOld: true
          device: 'all'
          outputDirectory: ./artifacts
          extraHeaders: '{"Cookie":"auth=${{ secrets.LHCI_FEAT_ACCESS_TOKEN }}"}'
      - name: Lighthouse Audit Staging
        uses: foo-software/lighthouse-check-action@master
        with:
          urls: 'https://recetastaging.vercel.app'
          gitAuthor: ${{ github.actor }}
          gitBranch: ${{ github.ref }}
          gitHubAccessToken: ${{ secrets.GITHUB_TOKEN }}
          prCommentEnabled: true
          prCommentSaveOld: true
          device: 'all'
          outputDirectory: ./artifacts
          extraHeaders: '{"Cookie":"auth=${{ secrets.LHCI_STAGING_ACCESS_TOKEN }}"}'
      - name: Lighthouse Audit Master
        uses: foo-software/lighthouse-check-action@master
        with:
          urls: 'https://receta.vercel.app'
          gitAuthor: ${{ github.actor }}
          gitBranch: ${{ github.ref }}
          gitHubAccessToken: ${{ secrets.GITHUB_TOKEN }}
          prCommentEnabled: true
          prCommentSaveOld: true
          device: 'all'
          outputDirectory: ./artifacts
          extraHeaders: '{"Cookie":"auth=${{ secrets.LHCI_FEAT_ACCESS_TOKEN }}"}'
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: Lighthouse reports
          path: ./artifacts
